### ISSUE TITLE
Keyboard broken on LineageOS 18.1 (Android 11)

### ISSUE THREAD

**Issue by StickyDigit** [bk138/multivnc#141] opened 2021-05-17 13:12 UTC
Mobile (Android): v.1.9.11
Installed from F-Droid
 LineageOS 18.1 (Android 11)
Nexus 7 (without Gapps)
OnePlus 3T (with Gapps).

Connected to an existing Tigervnc server which has worked ok in the past with MultiVNC. The keyboard appears and works for password, but once connected, any attempt to summon it via the menu results in it appearing for only a fraction of a second.

It works with  "Remote Keyboard" and "WiFi Keyboard", so I'm guessing it's a problem with on-screen keyboards.

It has worked in the past, but that may have been before I upgraded them from Android 10/9 to Android 11. I've not used MultiVNC for some months,

**Comment by bk138** [comment] 2021-05-18 18:14
Please try with AnySoft Keyboard which works for me on Android 11.

**Comment by StickyDigit** [comment] 2021-05-18 19:34
I don't see the actual keyboard in F-droid. Doesn't seem to be a UK English pack there either. Ah wait! There! it's tucked away in F-Droid as "Hungarian for AnySoftKeyboard". Bonkers!

Nope. That also vanishes instantly on both devices.

I've tried AOSP, Hacker's, and T16Fling too.

**Comment by bk138** [comment] 2021-05-18 19:54
Just tried with Hacker's Keyboard on Android 11, worksforme.

**Comment by StickyDigit** [comment] 2021-05-18 20:00
Both devices are LineageOS 18.1 official, One has MindTheGapps, the other does not.
I'll try it on all the rest of my droid-heap :-)

**Comment by StickyDigit** [comment] 2021-05-18 21:32
I reckon it's specific to LOS 18.1 or AOSP if other A11 users have no probs.

Also fails on unofficial LineageOS 18.1 on i9195. No Gapps.

Works fine in a few unofficial LOS 14's (Android 7). No Gapps.

Checking a LOS 17.1 official (Android 10). NoGapps. Works.

So. Three different LineageOS 18.1's fail. Two official (one of those with MindTheGapps) and one unofficial (no Gapps). Tried a few keyboards. All on screen fail so far.

Anyone got on-screen keyboard functioning on LOS 18.1 in MultiVNC?
 

On 18 May 2021 20:54:25 BST, Christian Beier ***@***.***> wrote:
>Just tried with Hacker's Keyboard on Android 11, worksforme. Might be specific to your device :-/
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/bk138/multivnc/issues/141#issuecomment-843510996
-- 
Sent from a phone. Please excuse my brevity.

**Comment by testman42** [comment] 2021-06-24 09:05
Can confirm, keyboard borked on LOS 18.1.
If there is anything more that I can do to help narrow down the issue, do let me know.

**Comment by mdnghtman** [comment] 2021-08-28 15:22
Can confirm this on LineageOS 18.1.
Bringing the Keyboard up from the menu results would fail.

Pressing long on the window itself would show three buttons on the top of the screen. Zoom Out, Keyboard and Zoom In.

Using this keyboard button the keyboard will persist. 

So, workaround for now. Hope this will help hunting it down.

**Comment by bk138** [comment] 2022-07-08 21:24
Actually #173 is a dupe of this, was fixed by 2012a798e706ab9814c2ae4a2f50a31324007db1.

**Closed by bk138** 2022-07-08 21:24 UTC
Labels: bug, platform-android

**Comment by sdspieg** [comment] 2022-08-11 22:29
> Pressing long on the window itself would show three buttons on the top of the screen. Zoom Out, Keyboard and Zoom In.

Which windows exactly?

**Comment by bk138** [comment] 2022-08-12 06:00
> > Pressing long on the window itself would show three buttons on the top of the screen. Zoom Out, Keyboard and Zoom In.
> 
> Which windows exactly?

The viewer's window, i.e. your whole phone screen.

**Comment by goofyseeker311** [comment] 2024-06-27 06:15
same issue with lineageos 20 on jetson nano 2gb.
keyboard broken in lock screen and on start screen, not in install or gettting started.
mouse does not work at all, even if its powered on like normal.
