### ISSUE TITLE
Keyboard layout fixed to US

### ISSUE THREAD

**Issue by anonimo82** [bk138/multivnc#198] opened 2022-06-18 13:13 UTC
**Is your bug report about the Desktop Multivnc or the Mobile MultiVNC?**
 - Desktop (wxWidgets) or Mobile (Android): Android 

**Which MultiVNC version are you using?**
 2.0.7

**Which server are you connecting to?**
 - VNC server vendor: unknown 
 - VNC server version: unknown 
 - OS version: unknown 
 - OS language: unknown 

**Describe the bug**

The keyboard layout in use (with physical keyboard) is always the US, regardless the system default or the user setting

**To Reproduce**

Plug a physical keyboard (either BlueTooth or USB), with a non-US layout.
Type some special character, like " or @.
You should see wrong output.

**Expected Behavior**

You should see typed characters according to your layout

**Screenshots**

None

**For the Desktop Version (please complete the following information):**
 - OS and version:
 - Xorg version used:
 - Wayland version used:

**For the Mobile Version (please complete the following information):**
 - Android version: Android Q
 - Installed from Play Store, F-Droid, Amazon Appstore: Play Store

**Additional context**

None

**Comment by bk138** [comment] 2022-06-18 14:04
Dupe of #138, me thinks. Let's collect info there.

**Closed by bk138** 2022-06-18 14:04 UTC
Labels: bug
